### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by pawlean** [paulienuh/25DaysOfGiphiness#1]
- [x] Understand how the GIPHY API works - Darren & @BioSok 

- [x] Create the index.html page 

- [x] Create styles for index page - _look at using CSS Grid_

- [x] Create an "About" team page

- [ ] Christmas songs? For the page!

- [ ] Buy domain name (if we succeed)

**Comment by darrenvong** [comment]
Omg we defo need a domain for this!
